import{createClient}from'https://esm.sh/@supabase/supabase-js@2.57.4';

const URL='https://hvpyngkqtqzvmweavego.supabase.co';
const KEY='sb_publishable_fZbTJCeuM8otLDnnoxRc9w_OGdZIXhX';
const sb=createClient(URL,KEY);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nameOf=m=>m?.nickname||m?.full_name||'Jugador';
const KEY_STATE='titanesTombolaStateV1';
let members=[],selected=new Set(),mode='manual',stage='players',remainingPlayers=[],pairs=[],currentPair=[],remainingPairs=[],matchups=[],currentMatch=[];
let observer=null,modal=null;

function secureRandomIndex(max){if(max<=1)return 0;const cryptoObj=globalThis.crypto;if(!cryptoObj?.getRandomValues)return Math.floor(Math.random()*max);const limit=Math.floor(0x100000000/max)*max;const a=new Uint32Array(1);do{cryptoObj.getRandomValues(a)}while(a[0]>=limit);return a[0]%max}
function drawOne(arr){if(!arr.length)return null;return arr.splice(secureRandomIndex(arr.length),1)[0]}
function shuffle(arr){let a=[...arr];for(let i=a.length-1;i>0;i--){let j=secureRandomIndex(i+1);[a[i],a[j]]=[a[j],a[i]]}return a}
function buzz(){try{navigator.vibrate?.([70,40,110])}catch(e){}}
function save(){try{localStorage.setItem(KEY_STATE,JSON.stringify({selected:[...selected],mode,stage,remainingPlayers:remainingPlayers.map(x=>x.id),pairs:pairs.map(p=>p.map(x=>x.id)),currentPair:currentPair.map(x=>x.id),remainingPairs:remainingPairs.map(p=>p.map(x=>x.id)),matchups:matchups.map(m=>m.map(p=>p.map(x=>x.id))),currentMatch:currentMatch.map(p=>p.map(x=>x.id))}))}catch(e){}}
function restore(){try{let s=JSON.parse(localStorage.getItem(KEY_STATE)||'{}'),byId=new Map(members.map(x=>[x.id,x]));if(Array.isArray(s.selected))selected=new Set(s.selected.filter(id=>byId.has(id)));mode=s.mode==='auto'?'auto':'manual';stage=['players','matches','done'].includes(s.stage)?s.stage:'players';remainingPlayers=(s.remainingPlayers||[]).map(id=>byId.get(id)).filter(Boolean);pairs=(s.pairs||[]).map(p=>p.map(id=>byId.get(id)).filter(Boolean)).filter(p=>p.length===2);currentPair=(s.currentPair||[]).map(id=>byId.get(id)).filter(Boolean);remainingPairs=(s.remainingPairs||[]).map(p=>p.map(id=>byId.get(id)).filter(Boolean)).filter(p=>p.length===2);matchups=(s.matchups||[]).map(m=>m.map(p=>p.map(id=>byId.get(id)).filter(Boolean)).filter(p=>p.length===2)).filter(Boolean);currentMatch=(s.currentMatch||[]).map(p=>p.map(id=>byId.get(id)).filter(Boolean)).filter(p=>p.length===2)}catch(e){}}
function resetDraw(keepSelection=true){stage='players';remainingPlayers=[];pairs=[];currentPair=[];remainingPairs=[];matchups=[];currentMatch=[];if(!keepSelection)selected.clear();save();renderModal()}
function pairLabel(p){return p?.length===2?`${esc(nameOf(p[0]))} + ${esc(nameOf(p[1]))}`:'—'}
function selectedMembers(){return members.filter(m=>selected.has(m.id))}
function validatePlayers(){let n=selected.size;if(n<4){alert('Selecciona por lo menos 4 jugadores.');return false}if(n%2!==0){alert('Para formar parejas debes seleccionar una cantidad par de jugadores.');return false}return true}
function startManual(){if(!validatePlayers())return;mode='manual';stage='players';remainingPlayers=shuffle(selectedMembers());pairs=[];currentPair=[];remainingPairs=[];matchups=[];currentMatch=[];save();renderModal()}
function drawManualPlayer(){if(stage!=='players')return;if(!remainingPlayers.length){finishPairs();return}let p=drawOne(remainingPlayers);currentPair.push(p);buzz();if(currentPair.length===2){pairs.push([...currentPair]);currentPair=[]}if(!remainingPlayers.length&&currentPair.length===0)finishPairs();save();renderModal(p?.id)}
function finishPairs(){stage='matches';remainingPairs=shuffle(pairs);currentMatch=[];save();renderModal()}
function drawManualPair(){if(stage!=='matches')return;if(!remainingPairs.length){stage='done';save();renderModal();return}let p=drawOne(remainingPairs);currentMatch.push(p);buzz();if(currentMatch.length===2){matchups.push([...currentMatch]);currentMatch=[]}if(!remainingPairs.length){if(currentMatch.length===1){matchups.push([...currentMatch]);currentMatch=[]}stage='done'}save();renderModal(null,p)}
function automaticAll(){if(!validatePlayers())return;mode='auto';let all=shuffle(selectedMembers());pairs=[];for(let i=0;i<all.length;i+=2)pairs.push([all[i],all[i+1]]);let pp=shuffle(pairs);matchups=[];for(let i=0;i<pp.length;i+=2)matchups.push(pp.slice(i,i+2));remainingPlayers=[];currentPair=[];remainingPairs=[];currentMatch=[];stage='done';buzz();save();renderModal()}
function toggle(id){selected.has(id)?selected.delete(id):selected.add(id);resetDraw(true)}
function selectAll(){selected=new Set(members.map(x=>x.id));resetDraw(true)}
function clearAll(){selected.clear();resetDraw(true)}
function closeModal(){modal?.remove();modal=null}

function styles(){if(document.getElementById('tombolaStyles'))return;let s=document.createElement('style');s.id='tombolaStyles';s.textContent=`
.tombolaLaunch{border:1px solid #ffcc33!important;background:linear-gradient(135deg,#2d1800,#4d2a00)!important;box-shadow:0 0 24px #ffcc3325!important}
.tombolaOverlay{position:fixed;inset:0;z-index:10020;background:#000d;backdrop-filter:blur(10px);display:flex;justify-content:center;align-items:flex-start;overflow:auto;padding:12px}
.tombolaPanel{width:min(760px,100%);margin:auto;background:radial-gradient(circle at 50% -10%,#332100,#07111f 38%,#04080d 100%);border:1px solid #8c6b1f;border-radius:24px;box-shadow:0 22px 80px #000,0 0 38px #ffcc3320;padding:16px;color:#f8fafc}
.tombolaHead{display:flex;gap:10px;align-items:center}.tombolaHead h1{margin:0;font-size:25px}.tombolaClose{border:0;background:#26384d;color:white;border-radius:12px;width:42px;height:42px;font-size:22px}.tombolaTabs{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:12px 0}.tombolaTab{border:1px solid #38516d;background:#091827;color:#fff;border-radius:14px;padding:12px;font-weight:1000}.tombolaTab.on{background:linear-gradient(135deg,#a26b00,#ffcc33);color:#111;border-color:#ffcc33}.tombolaCard{border:1px solid #294765;background:#081522;border-radius:18px;padding:13px;margin:10px 0}.tombolaPlayers{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px;max-height:300px;overflow:auto}.tombolaPlayer{border:1px solid #334863;background:#0b1a2a;color:#fff;border-radius:13px;padding:10px;text-align:left;font-weight:800}.tombolaPlayer.on{border-color:#58ff18;background:#10230d;box-shadow:0 0 15px #58ff1822}.tombolaActions{display:flex;gap:7px;flex-wrap:wrap}.tombolaBtn{border:0;border-radius:14px;padding:12px 14px;font-weight:1000;background:#ffcc33;color:#111;min-height:46px}.tombolaBtn.green{background:#19c37d}.tombolaBtn.blue{background:#3b82f6;color:#fff}.tombolaBtn.dark{background:#294765;color:#fff}.tombolaBtn.red{background:#ef4444;color:#fff}.tombolaBtn:disabled{opacity:.45}.tombolaBall{width:122px;height:122px;border-radius:50%;margin:12px auto;display:grid;place-items:center;text-align:center;padding:10px;background:radial-gradient(circle at 35% 30%,#fff7bf,#ffcc33 38%,#a56700 78%);color:#111;border:5px solid #ffe681;box-shadow:0 0 36px #ffcc3355;font-weight:1000;animation:tombolaPop .5s ease}.tombolaPair{border:1px solid #334863;border-radius:13px;padding:10px;margin:7px 0;background:#07111f}.tombolaMatch{border:1px solid #7c2dff;border-radius:16px;padding:12px;margin:9px 0;background:linear-gradient(135deg,#17102b,#07111f)}.tombolaVS{text-align:center;color:#ffcc33;font-size:20px;font-weight:1000;margin:4px}.tombolaCount{font-size:12px;color:#9fb0c4}.tombolaStep{display:grid;grid-template-columns:34px 1fr;gap:8px;align-items:center;margin:7px 0}.tombolaStep b:first-child{width:32px;height:32px;border-radius:50%;display:grid;place-items:center;background:#ffcc33;color:#111}.tombolaDone{text-align:center;padding:18px;border:1px solid #19c37d;border-radius:16px;background:#0a2a20}.tombolaResultTitle{display:flex;align-items:center;gap:8px}.tombolaResultTitle h3{margin:0;flex:1}@keyframes tombolaPop{0%{transform:scale(.2) rotate(-180deg);opacity:.2}70%{transform:scale(1.1) rotate(8deg)}100%{transform:scale(1) rotate(0)}}
@media(max-width:520px){.tombolaPlayers{grid-template-columns:1fr}.tombolaPanel{padding:12px}.tombolaHead h1{font-size:21px}.tombolaBall{width:108px;height:108px}}
`;document.head.appendChild(s)}

function selectionHtml(){return`<div class="tombolaCard"><div class="tombolaResultTitle"><h3>👥 Jugadores participantes</h3><span class="tombolaCount">${selected.size} seleccionados</span></div><div class="tombolaActions"><button class="tombolaBtn dark" data-t="all">Seleccionar todos</button><button class="tombolaBtn dark" data-t="clear">Limpiar</button></div><div class="tombolaPlayers">${members.map(m=>`<button class="tombolaPlayer ${selected.has(m.id)?'on':''}" data-player="${m.id}">${selected.has(m.id)?'✅':'○'} ${esc(nameOf(m))}<div class="tombolaCount">${esc(m.full_name||'Miembro del club')}</div></button>`).join('')}</div></div>`}
function pairsHtml(){return pairs.length?`<div class="tombolaCard"><div class="tombolaResultTitle"><h3>🤝 Parejas sorteadas</h3><span class="tombolaCount">${pairs.length}</span></div>${pairs.map((p,i)=>`<div class="tombolaPair"><b>Pareja ${i+1}</b><br>${pairLabel(p)}</div>`).join('')}</div>`:''}
function matchesHtml(){return matchups.length?`<div class="tombolaCard"><div class="tombolaResultTitle"><h3>⚔️ Enfrentamientos</h3><span class="tombolaCount">${matchups.length}</span></div>${matchups.map((m,i)=>m.length===2?`<div class="tombolaMatch"><b>Mesa ${i+1}</b><div>${pairLabel(m[0])}</div><div class="tombolaVS">VS</div><div>${pairLabel(m[1])}</div></div>`:`<div class="tombolaMatch"><b>Pase libre</b><div>${pairLabel(m[0])}</div><div class="tombolaCount">Esta pareja queda libre en esta ronda.</div></div>`).join('')}</div>`:''}
function manualHtml(highlightId=null,highlightPair=null){if(!remainingPlayers.length&&!pairs.length&&stage==='players')return`<div class="tombolaCard"><h3>🎯 Manual · paso a paso</h3><div class="tombolaStep"><b>1</b><span>Selecciona los jugadores.</span></div><div class="tombolaStep"><b>2</b><span>Saca <b>un jugador a la vez</b>. Cada dos jugadores se forma una pareja.</span></div><div class="tombolaStep"><b>3</b><span>Después saca <b>una pareja a la vez</b> para formar los enfrentamientos.</span></div><button class="tombolaBtn green" data-t="startManual">🎰 Iniciar sorteo manual</button></div>`;
 if(stage==='players'){let last=highlightId?members.find(x=>x.id===highlightId):null;return`<div class="tombolaCard"><h3>🎰 Paso 1 · Formando parejas</h3><div class="tombolaCount">Quedan ${remainingPlayers.length} jugadores en la tómbola · ${pairs.length} parejas completas</div>${last?`<div class="tombolaBall">${esc(nameOf(last))}</div>`:''}${currentPair.length?`<div class="tombolaPair"><b>Pareja en formación</b><br>${currentPair.map(nameOf).map(esc).join(' + ')} + ?</div>`:''}<button class="tombolaBtn green" data-t="drawPlayer" ${!remainingPlayers.length?'disabled':''}>🎲 Sacar siguiente jugador</button></div>`}
 if(stage==='matches'){return`<div class="tombolaCard"><h3>⚔️ Paso 2 · Sorteando enfrentamientos</h3><div class="tombolaCount">Quedan ${remainingPairs.length} parejas en la tómbola</div>${highlightPair?`<div class="tombolaBall">${pairLabel(highlightPair)}</div>`:''}${currentMatch.length?`<div class="tombolaMatch"><b>Enfrentamiento en formación</b><div>${pairLabel(currentMatch[0])}</div><div class="tombolaVS">VS</div><div>?</div></div>`:''}<button class="tombolaBtn blue" data-t="drawPair" ${!remainingPairs.length?'disabled':''}>⚔️ Sacar siguiente pareja</button></div>`}
 return`<div class="tombolaDone"><div style="font-size:42px">🏆</div><h2>Sorteo completado</h2><p>Las parejas y los enfrentamientos quedaron definidos.</p><button class="tombolaBtn" data-t="reset">🔄 Hacer otro sorteo</button></div>`}
function autoHtml(){return`<div class="tombolaCard"><h3>⚡ Automático completo</h3><p class="tombolaCount">Con un solo toque Titanes Dominó mezclará los jugadores, formará todas las parejas y sorteará todos los enfrentamientos.</p><button class="tombolaBtn green" data-t="automatic">⚡ SORTEAR TODO AUTOMÁTICAMENTE</button></div>${stage==='done'?`<div class="tombolaDone"><div style="font-size:42px">🎉</div><h2>¡Listo!</h2><p>Todo el proceso se hizo automáticamente.</p><button class="tombolaBtn" data-t="reset">🔄 Repetir sorteo</button></div>`:''}`}
function renderModal(highlightId=null,highlightPair=null){if(!modal)return;modal.innerHTML=`<div class="tombolaPanel"><div class="tombolaHead"><div style="font-size:34px">🎰</div><div style="flex:1"><h1>Tómbola Titanes</h1><div class="tombolaCount">Parejas + enfrentamientos</div></div><button class="tombolaClose" data-t="close">×</button></div><div class="tombolaTabs"><button class="tombolaTab ${mode==='manual'?'on':''}" data-mode="manual">👆 Paso a paso</button><button class="tombolaTab ${mode==='auto'?'on':''}" data-mode="auto">⚡ Automático</button></div>${selectionHtml()}${mode==='manual'?manualHtml(highlightId,highlightPair):autoHtml()}${pairsHtml()}${matchesHtml()}</div>`;bindModal()}
function bindModal(){modal.querySelectorAll('[data-player]').forEach(b=>b.onclick=()=>toggle(b.dataset.player));modal.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;resetDraw(true)});modal.querySelectorAll('[data-t]').forEach(b=>b.onclick=()=>{let a=b.dataset.t;if(a==='close')closeModal();if(a==='all')selectAll();if(a==='clear')clearAll();if(a==='startManual')startManual();if(a==='drawPlayer')drawManualPlayer();if(a==='drawPair')drawManualPair();if(a==='automatic')automaticAll();if(a==='reset')resetDraw(true)})}
async function openTombola(){styles();if(!members.length){let r=await sb.from('members').select('id,full_name,nickname').eq('active',true).is('deleted_at',null).order('nickname',{ascending:true});if(r.error)return alert('No se pudo cargar la lista de jugadores: '+r.error.message);members=r.data||[];restore();if(!selected.size)selected=new Set(members.map(x=>x.id))}modal=document.createElement('div');modal.className='tombolaOverlay';document.body.appendChild(modal);renderModal()}
function injectLauncher(){styles();let hero=[...document.querySelectorAll('.hero')].find(x=>x.textContent.includes('MÁS'));if(!hero)return;let root=hero.parentElement;if(!root||root.querySelector('.tombolaLaunch'))return;let firstTile=root.querySelector('.tile.full[data-a="sub"]');let b=document.createElement('button');b.type='button';b.className='tile full tombolaLaunch';b.style.cssText='text-align:left;color:white;font-weight:1000';b.innerHTML='🎰 Tómbola de Sorteos <span style="float:right">→</span><div class="tombolaCount">Manual paso a paso o automático completo</div>';b.onclick=openTombola;if(firstTile)root.insertBefore(b,firstTile);else hero.insertAdjacentElement('afterend',b)}
function startObserver(){injectLauncher();observer=new MutationObserver(()=>injectLauncher());observer.observe(document.getElementById('root')||document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',startObserver);else startObserver();
