// Titanes Dominó · Control por voz V1
// Navegación, búsqueda, tómbola, retadores y asistencia de anotación.
const SR=window.SpeechRecognition||window.webkitSpeechRecognition;
let rec=null,listening=false,voiceBtn=null,voiceBox=null;
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9ñ ]/g,' ').replace(/\s+/g,' ').trim();
function say(t){try{speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang='es-DO';u.rate=1.05;speechSynthesis.speak(u)}catch(e){}}
function toast(t){let x=document.createElement('div');x.className='voiceToast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),2800)}
function clickText(sel,words){let w=norm(words);let el=[...document.querySelectorAll(sel)].find(x=>norm(x.textContent).includes(w));if(el){el.click();return true}return false}
function go(label){let target=norm(label);let el=[...document.querySelectorAll('button,[data-a],nav *')].find(x=>norm(x.textContent)===target||norm(x.textContent).includes(target));if(el){el.click();return true}return false}
function openTombola(){let b=document.querySelector('.tombolaLaunch');if(b){b.click();return true}if(go('mas')){setTimeout(()=>document.querySelector('.tombolaLaunch')?.click(),250);return true}return false}
function confirmVoice(question,fn){say(question+' Di confirmar para continuar.');pending={fn,until:Date.now()+8000};toast('⚠️ '+question+' · di “confirmar”')}
let pending=null;
function searchPlayer(name){let inputs=[...document.querySelectorAll('input')];let i=inputs.find(x=>/buscar|jugador|nombre/i.test((x.placeholder||'')+' '+(x.getAttribute('aria-label')||'')));if(!i){toast('Abre una pantalla con búsqueda de jugadores.');return false}i.focus();i.value=name;i.dispatchEvent(new Event('input',{bubbles:true}));i.dispatchEvent(new Event('change',{bubbles:true}));return true}
function scoreCommand(t){let m=t.match(/(?:anota|anotar|pon|poner)\s+(\d{1,3})\s+(?:a|para)\s+(largos|cortos)/);if(!m)return false;let pts=m[1],team=m[2];let buttons=[...document.querySelectorAll('button')];let teamEl=buttons.find(b=>norm(b.textContent).includes(team)&&norm(b.textContent).includes(pts));if(teamEl){confirmVoice(`Confirmar ${pts} puntos para ${team}`,()=>teamEl.click());return true}let manual=buttons.find(b=>/manual/i.test(b.textContent));if(manual){manual.click();setTimeout(()=>{let inp=[...document.querySelectorAll('input[type="number"],input')].find(x=>x.offsetParent!==null);if(inp){inp.value=pts;inp.dispatchEvent(new Event('input',{bubbles:true}));toast(`${pts} puntos preparados para ${team}. Confirma en pantalla.`)}},150);return true}toast(`No encontré el control de ${team} en la pantalla actual.`);return true}
function command(raw){let t=norm(raw);toast('🎙️ '+raw);if(pending&&Date.now()<pending.until&&/^(confirmar|confirmo|si confirmar|si)$/.test(t)){let f=pending.fn;pending=null;say('Confirmado');f();return}if(/cancelar|no confirmar/.test(t)){pending=null;say('Cancelado');return}
 if(scoreCommand(t))return;
 if(t.includes('abrir tombola')||t==='tombola'){openTombola();return}
 if(t.includes('sortear todo')){if(!document.querySelector('.tombolaOverlay'))openTombola();setTimeout(()=>clickText('[data-mode]','automatico')&&setTimeout(()=>clickText('[data-t="automatic"]','sortear'),100),250);return}
 if(t.includes('siguiente jugador')||t.includes('sacar jugador')){clickText('[data-t="drawPlayer"]','sacar')||toast('Inicia primero el sorteo manual.');return}
 if(t.includes('siguiente pareja')||t.includes('sacar pareja')){clickText('[data-t="drawPair"]','sacar')||toast('Aún no estás sorteando enfrentamientos.');return}
 let s=t.match(/buscar\s+(?:jugador\s+)?(.+)/);if(s){searchPlayer(s[1]);return}
 if(t.includes('retadores')||t.includes('turnos')){go('mas');setTimeout(()=>go('retadores')||go('turnos'),180);return}
 if(t.includes('estadisticas')){go('mas');setTimeout(()=>go('estadisticas'),180);return}
 if(t.includes('ranking')){go('ranking');return}if(t.includes('partidas')||t.includes('partida')){go('partidas');return}if(t.includes('chat')){go('chat');return}if(t.includes('inicio')){go('inicio');return}if(t==='mas'||t.includes('menu mas')){go('mas');return}
 if(t.includes('corregir ultima')||t.includes('borrar ultima')||t.includes('anular ultima')){let b=[...document.querySelectorAll('button')].find(x=>/corregir|borrar|anular/i.test(x.textContent));if(b)confirmVoice('¿Confirmas modificar la última anotación?',()=>b.click());else toast('No encontré una anotación modificable en esta pantalla.');return}
 toast('No reconocí ese comando. Toca 🎙️ y prueba de nuevo.');say('No reconocí el comando')}
function stop(){try{rec?.stop()}catch(e){}listening=false;voiceBtn?.classList.remove('on')}
function start(){if(!SR){toast('El reconocimiento de voz no está disponible en este navegador.');return}if(listening){stop();return}if(!rec){rec=new SR();rec.lang='es-DO';rec.interimResults=false;rec.continuous=false;rec.maxAlternatives=3;rec.onresult=e=>{let r=e.results[e.results.length-1];command(r[0].transcript)};rec.onerror=e=>{if(e.error!=='aborted')toast('Micrófono: '+e.error)};rec.onend=()=>{listening=false;voiceBtn?.classList.remove('on')}}try{rec.start();listening=true;voiceBtn.classList.add('on');toast('🎙️ Te escucho…')}catch(e){}}
function styles(){let s=document.createElement('style');s.textContent=`.voiceFab{position:fixed;right:16px;bottom:86px;z-index:10010;width:58px;height:58px;border-radius:50%;border:1px solid #62e8ff;background:radial-gradient(circle at 35% 25%,#26d8ff,#08395d 60%,#061522);color:white;font-size:25px;box-shadow:0 0 28px #25d9ff66}.voiceFab.on{animation:vp 1s infinite;box-shadow:0 0 42px #58ff18}.voiceToast{position:fixed;z-index:11000;left:50%;bottom:155px;transform:translateX(-50%);max-width:min(90vw,520px);background:#071522ee;border:1px solid #36d7ff;color:white;border-radius:14px;padding:11px 14px;font-weight:800;text-align:center;box-shadow:0 12px 35px #0009}@keyframes vp{50%{transform:scale(1.12)}}`;document.head.appendChild(s)}
function init(){styles();voiceBtn=document.createElement('button');voiceBtn.type='button';voiceBtn.className='voiceFab';voiceBtn.setAttribute('aria-label','Mando por voz');voiceBtn.title='Mando por voz';voiceBtn.textContent='🎙️';voiceBtn.onclick=start;document.body.appendChild(voiceBtn)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
